import dotenv from 'dotenv';
dotenv.config();

export default {
  PORT: process.env.PORT || 5000,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  OPENAI_MODEL: "text-embedding-ada-002",
  MILVUS_ADDRESS: process.env.MILVUS_ADDRESS || "localhost:19530",
  MONGODB_URL: process.env.MONGODB_URL,
  MONGODB_USER: process.env.MONGODB_USER,
  MONGODB_PASSWORD: process.env.MONGODB_PASSWORD,
  REDIS_HOST: process.env.REDIS_HOST || "localhost",
  REDIS_PORT: process.env.REDIS_PORT || 6379,
  EMBEDDING_DIMENSION: 1536,
  MAX_TEXT_LENGTH: 65535,
  CHUNK_SIZE: 3000,
  CHUNK_OVERLAP: 50,
  MILVUS_NPROBE: 10,
  MILVUS_TOP_K: 2,
  MILVUS_RETURN_COUNT: 2,
  MILVUS_NLIST: 128,
  MAX_RETRIES: 10,
  RETRY_DELAY: 2000, // in milliseconds
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
  MODELSTOCREDITS: {
    'gpt-4o-mini': 1,
    'GPT-4o Mini': 1,
    'Llama 4 Maverick': 2,
    'llama-4-maverick': 2,
    'GPT-3.5 Turbo': 1,
    'Llama 3 Pro': 3,
    'Gemini Ultra': 4,
    'Claude 3 Opus': 5,
    'Mistral Large': 6,
    'Mixtral 8x22B': 7,
    'Grok-1': 8
  },
  PLANS: [
    {
      id: "1",
      name: "STARTER",
      price: 0,
      totalPrice: 0,
      totalDocSize: 512000,
      currency: "USD",
      credits: 100,
      recurrence: "monthly",
      agentLimit: 1,
      lookupKey: "starter",
      description: "per month",
      features: [
        '1 Hosted AI Agent',
        'Standard Models',
        '100 Tokens / Month',
        '3 AI Actions per Agents',
        '500KB Data Uploads per Agent',
        'Calendar & Bookings',
        'Commerce Support',
        'Booking & Calendar Sync',
        'Digital Products',
        'Subscriptions',
        'Basic Analytics',
        '1 Team Members',
        'Email Support',
        'Embeddable Agent',
        'Agent Deletion on Inactivity (14 days)'
      ]
    },
    {
      id: "2",
      name: "SOLO",
      price: 29,
      totalPrice: 29,
      totalDocSize: 5242880,
      currency: "USD",
      credits: 1000,
      description: "per month",
      recurrence: "monthly",
      agentLimit: 3,
      lookupKey: "solo_monthly",
      features: [
        'everyting in FREE +',
        'Advanced Models',
        '1000 Tokens / Month',
        '5 AI Actions per Agents',
        '5MB Data Uploads per Agent',
        'Service & Downloads',
        'Digital Products (PDF, Video, ZIP)',
        'Email / Whatsapp Marketing',
      ]
    },
    {
      id: "3",
      name: "PRO",
      price: 99,
      totalPrice: 99,
      totalDocSize: 52428800,
      currency: "USD",
      credits: 5000,
      description: "per month",
      recurrence: "monthly",
      agentLimit: 3,
      lookupKey: "pro_monthly",
      features: [
        'everyting in SOLO +',
        '3 Agents',
        'Full Suite Models',
        '5000 Tokens / Month',
        '10 AI Actions per Agents',
        '50MB Data Uploads per Agent',
        'Subscriptions, Tipping',
        'Paid Bookings',
        'Digital Products (All formats)',
        'Basic Integrations (MCP)',
        'Advanced Analytics',
        'Upto 3 Team Members',
        'Priority Email Support'
      ]
    },
    {
      id: "4",
      name: "BUSINESS",
      price: 499,
      totalPrice: 499,
      totalDocSize: 52428800,
      currency: "USD",
      credits: 20000,
      description: "per month",
      agentLimit: 9999,
      lookupKey: "business_monthly",
      recurrence: "monthly",
      features: [
        'everyting in PRO +',
        'Unlimited Agents',
        '20000 Tokens / Month',
        '15 AI Actions per Agents',
        'All Commerce Support',
        'Advanced Agents Integrations (MCP)',
        '10 + Team Members',
        'Dedicated Email Support'
      ]
    },
    {
      id: "5",
      name: "STARTER",
      price: 0,
      totalPrice: 0,
      totalDocSize: 512000,
      currency: "USD",
      credits: 100,
      recurrence: "yearly",
      agentLimit: 1,
      lookupKey: "starter_yearly",
      description: "per month",
      features: [
        '1 Hosted AI Agent',
        'Standard Models',
        '100 Tokens / Month',
        '3 AI Actions per Agents',
        '500KB Data Uploads per Agent',
        'Calendar & Bookings',
        'Commerce Support',
        'Booking & Calendar Sync',
        'Digital Products',
        'Subscriptions',
        'Basic Analytics',
        '1 Team Members',
        'Email Support',
        'Embeddable Agent',
        'Agent Deletion on Inactivity (14 days)'
      ]
    },
    {
      id: "6",
      name: "SOLO(YEARLY)",
      price: 19,
      totalPrice: 228,
      totalDocSize: 5242880,
      description: "per month, $228 billed yearly",
      currency: "USD",
      credits: 12000,
      recurrence: "yearly",
      agentLimit: 1,
      lookupKey: "solo_yearly",
      features: [
        'everyting in FREE +',
        'Advanced Models',
        '1000 Tokens / Month',
        '5 AI Actions per Agents',
        '5MB Data Uploads per Agent',
        'Service & Downloads',
        'Digital Products (PDF, Video, ZIP)',
        'Email / Whatsapp Marketing',
      ]
    },
    {
      id: "7",
      name: "PRO(YEARLY)",
      price: 79,
      totalPrice: 948,
      totalDocSize: 52428800,
      description: "per month, $948 billed yearly",
      currency: "USD",
      credits: 60000,
      recurrence: "yearly",
      agentLimit: 3,
      lookupKey: "pro_yearly",
      features: [
        'everyting in SOLO +',
        '3 Agents',
        'Full Suite Models',
        '5000 Tokens / Month',
        '10 AI Actions per Agents',
        '50MB Data Uploads per Agent',
        'Subscriptions, Tipping',
        'Paid Bookings',
        'Digital Products (All formats)',
        'Basic Integrations (MCP)',
        'Advanced Analytics',
        'Upto 3 Team Members',
        'Priority Email Support'
      ]
    },
    {
      id: "8",
      name: "BUSINESS(YEARLY)",
      price: 399,
      totalPrice: 4788,
      totalDocSize: 52428800,
      description: "per month, $4788 billed yearly",
      currency: "USD",
      credits: 240000,
      recurrence: "yearly",
      agentLimit: 9999,
      lookupKey: "business_yearly",
      features: [
        'everyting in PRO +',
        'Unlimited Agents',
        '20000 Tokens / Month',
        '15 AI Actions per Agents',
        'All Commerce Support',
        'Advanced Agents Integrations (MCP)',
        '10 + Team Members',
        'Dedicated Email Support'
      ]
    }
  ],
};